version: "3.7"

services:
  database:
    image: mysql:8.0
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=swordfish
    ports:
      - "3306:3306"
    restart: always

  ingestion-container:
    image: ingestion-container
    build: images/ingestion-container
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - ./data:/data

  summary-container:
    image: summary-container
    build: images/summary-container
    environment:
      - PYTHONIOENCODING=utf-8
    volumes:
      - ./data:/data

  example-c:
    image: example-c
    build: images/example-c
    volumes:
      - ./data:/data

  example-node:
    image: example-node
    build: images/example-node
    volumes:
      - ./data:/data

  example-python:
    image: example-python
    build: images/example-python
    volumes:
      - ./data:/data

  example-r:
    image: example-r
    build: images/example-r
    volumes:
      - ./data:/data

  example-ruby:
    image: example-ruby
    build: images/example-ruby
    volumes:
      - ./data:/data

  example-rust:
    image: example-rust
    build: images/example-rust
    volumes:
      - ./data:/data

  example-swift:
    image: example-swift
    build: images/example-swift
    volumes:
      - ./data:/data
